name: Android Builds

on:
  workflow_call:
  workflow_dispatch:

env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
    swappy=yes

jobs:
  build-android:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            cache-name: android-editor
            target: editor
            scons-flags: >-
              arch=arm64
              production=yes

          - name: Template arm32 (target=template_release, arch=arm32)
            cache-name: android-template-arm32
            target: template_release
            scons-flags: arch=arm32

          - name: Template arm64 (target=template_release, arch=arm64)
            cache-name: android-template-arm64
            target: template_release
            scons-flags: arch=arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download Swappy
        run: python ./misc/scripts/install_swappy_android.py

      - name: Load Encryption Key
        id: load_key
        run: |
          if [ ! -f godot.gdkey ]; then
            echo "错误：找不到 godot.gdkey 文件"
            exit 1
          fi
          
          key=$(cat godot.gdkey | tr -d '[:space:]')
          
          if [ ${#key} -ne 64 ]; then
            echo "错误：密钥长度不正确"
            exit 1
          fi
          
          key=$(echo "$key" | tr '[:upper:]' '[:lower:]')
          echo "SCRIPT_AES256_ENCRYPTION_KEY=$key" >> $GITHUB_ENV

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} script_encryption_key="$SCRIPT_AES256_ENCRYPTION_KEY"
          platform: android
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Generate Godot templates
        if: matrix.target == 'template_release'
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Generate Godot editor
        if: matrix.target == 'editor'
        run: |
          cd platform/android/java
          ./gradlew generateGodotEditor
          ./gradlew generateGodotHorizonOSEditor
          ./gradlew generateGodotPicoOSEditor
          cd ../../..
          ls -l bin/android_editor_builds/
          
          mkdir horizonos
          mv bin/android_editor_builds/*-horizonos-* horizonos || true
          mkdir picoos
          mv bin/android_editor_builds/*-picoos-* picoos || true

      - name: Prepare artifacts (exclude obj)
        run: |
          rm -rf bin/obj || true
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      - name: Upload artifact (Horizon OS)
        if: matrix.target == 'editor'
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-horizonos
          path: horizonos

      - name: Upload artifact (PICO OS)
        if: matrix.target == 'editor'
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-picoos
          path: picoos
