name: iOS Builds

on:
  workflow_call:
  workflow_dispatch:

env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
    debug_symbols=no

jobs:
  ios-template:
    runs-on: macos-latest
    name: Template (target=template_release)
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Load Encryption Key
        id: load_key
        run: |
          if [ ! -f godot.gdkey ]; then
            echo "错误：找不到 godot.gdkey 文件"
            exit 1
          fi
          
          key=$(cat godot.gdkey | tr -d '[:space:]')
          
          if [ ${#key} -ne 64 ]; then
            echo "错误：密钥长度不正确"
            exit 1
          fi
          
          key=$(echo "$key" | tr '[:upper:]' '[:lower:]')
          echo "SCRIPT_AES256_ENCRYPTION_KEY=$key" >> $GITHUB_ENV

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} script_encryption_key="$SCRIPT_AES256_ENCRYPTION_KEY"
          platform: ios
          target: template_release

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        continue-on-error: true

      - name: Prepare artifacts (exclude obj)
        run: |
          rm -rf bin/obj || true
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-template
