name: 🏁 Windows Builds

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target'
        type: choice
        options:
          - editor
          - template_release
        default: 'editor'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup SCons
        run: pip install scons

      - name: Build Godot
        run: scons platform=windows target=${{ inputs.target }} d3d12=no

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-${{ inputs.target }}-windows
          path: bin/